### ISSUE TITLE
Convert_models.sh not working

### ISSUE THREAD

**Issue by flexbeats** [jario-jin/yolov5-on-nvidia-jetson#4]
I tried to launch the script but it fails

`jetson-iot@jetsoniot-desktop:~/yolov5-on-nvidia-jetson$ bash scripts/convert_models.sh
\033[31m[ERROR]: models not exist!: \033[0m
Downloading...
From: https://drive.google.com/uc?id=1i3RkUlz7KRV0F3y0uNownPjUMPmXCr5b
To: /home/jetson-iot/yolov5-on-nvidia-jetson/models/yolov5s.pt
100%|████████████████████████████████████████████████████████████████████████████████| 14.8M/14.8M [00:01<00:00, 7.50MB/s]
Traceback (most recent call last):
  File "generator.py", line 5, in <module>
    from utils.torch_utils import select_device
  File "/home/jetson-iot/yolov5-on-nvidia-jetson/yolov5/utils/torch_utils.py", line 18, in <module>
    import torchvision
ModuleNotFoundError: No module named 'torchvision'
mv: cannot stat 'models/yolov5s.wts': No such file or directory
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: /usr/local/cuda (found version "10.2") 
-- Found OpenCV: /usr (found version "4.1.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jetson-iot/yolov5-on-nvidia-jetson/build
[ 20%] Building NVCC (Device) object CMakeFiles/myplugins.dir/src/myplugins_generated_yololayer.cu.o
/home/jetson-iot/yolov5-on-nvidia-jetson/src/yololayer.h(94): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int, const nvinfer1::Dims *, int, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

/home/jetson-iot/yolov5-on-nvidia-jetson/src/yololayer.h(94): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int, const nvinfer1::Dims *, int, const nvinfer1::DataType *, const nvinfer1::DataType *, const bool *, const bool *, nvinfer1::PluginFormat, int)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

Scanning dependencies of target myplugins
[ 40%] Linking CXX shared library libmyplugins.so
[ 40%] Built target myplugins
Scanning dependencies of target yolov5
[ 60%] Building CXX object CMakeFiles/yolov5.dir/src/calibrator.cpp.o
[ 80%] Building CXX object CMakeFiles/yolov5.dir/src/yolov5.cpp.o
/home/jetson-iot/yolov5-on-nvidia-jetson/src/yolov5.cpp: In function ‘int main(int, char**)’:
/home/jetson-iot/yolov5-on-nvidia-jetson/src/yolov5.cpp:379:11: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
     system("rm -r annotations");
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/jetson-iot/yolov5-on-nvidia-jetson/src/yolov5.cpp:380:11: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
     system("mkdir -p annotations");
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
[100%] Linking CXX executable yolov5
[100%] Built target yolov5
Loading weights: yolov5s.wts
yolov5: /home/jetson-iot/yolov5-on-nvidia-jetson/src/common.hpp:94: std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights> loadWeights(std::__cxx11::string): Assertion `input.is_open() && "Unable to load weight file. please check if the .wts file path is right!!!!!!"' failed.
scripts/convert_models.sh: line 25:  2027 Aborted                 sudo ./yolov5 -s ${model_name}.wts ${model_name}.engine s
`

**Comment by flexbeats** [comment]
I followed this procedue to install pytorch
[https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-10-now-available/72048](url)
